### ISSUE TITLE
Error de CSS FAQ

### ISSUE THREAD

**Issue by iLestar** [KrlosPK/webfam#6]
En el apartado de Preguntas Frecuentes, ubicado hasta el final de la página de Inicio; donde claramente podemos apreciar cómo se mueven las cards al dar click. 
**Vista default de las cards**
![imagen](https://user-images.githubusercontent.com/71247432/221584108-e9e0af9d-98c3-43b2-84e3-814bb01e71ab.png)
**Vista de la card activada**
![imagen](https://user-images.githubusercontent.com/71247432/221584191-bb073952-ba31-492b-896b-0d841eb6dd29.png)

**Comment by KrlosPK** [comment]
Lito 👍
